### ISSUE TITLE
Migrating from jekyll-now?

### ISSUE THREAD

**Issue by AdmiralAsshat** [amitmerchant1990/reverie#13]
For anyone that has decided to follow your fork of jekyll-now, do you have any migration instructions? Are there specific files I can simply replace in my existing blog project, or do you recommend just doing a nuke-and-pave for everything but the posts?

**Comment by amitmerchant1990** [comment]
I guess just doing a nuke-and-pave for everything but the posts cause replacing things will be too much of a work as Reverie has much more functionality than Jekyll Now. So, it would be a better idea to start from the scratch.
