### ISSUE TITLE
jekyll-scholar

### ISSUE THREAD

**Issue by evinpinar** [amitmerchant1990/reverie#16]
Currently, I am trying to add some references/bibliography to my blog post through jekyll-scholar. It is working fine on local, but github cannot recognize the citations(the plugin is not recognized). How can I solve this problem? 

Specifically, github returns this error:

The tag cite on line 1 in _posts/.....md is not a recognized Liquid tag.

Where cite is used as shown [here](https://github.com/inukshuk/jekyll-scholar#usage).

**Comment by amitmerchant1990** [comment]
jekyll-scholar is not supported by GitHub Pages natively. If you want to use the same on your site, you should think about migrating it to [Netlify](https://www.netlify.com/) or something like that.
