### ISSUE TITLE
Any way to make images open in popup

### ISSUE THREAD

**Issue by socialstijn** [amitmerchant1990/reverie#17]
I want to show some large images in my blog. Any change to have these opened in a sort of lightbox kinda way?

Great template, thanks!https://guides.github.com/features/mastering-markdown/

**Comment by amitmerchant1990** [comment]
Currently, no. It doesn't support to show images as a lightbox. I've kept Reverie minimalistic and lightweight purposefully. But you can easily [integrate lightbox](https://jekyllcodex.org/without-plugin/lightbox/#) in your own implementation.
