### ISSUE TITLE
How to set About section to "primary" page? 

### ISSUE THREAD

**Issue by julianstastny** [amitmerchant1990/reverie#19]
Hi,
I am not familiar with HTML, so please excuse if this is really stupid and trivial - But how would I set the About section to be the primary page, in the sense that it is the one that appears first if one calls "username.github.io" or clicks on the logo or blog title?

Thanks in advance!

**Comment by codestin** [comment]
The first answer with the green checkmark here may solve your issue in a hack-y way:
[https://stackoverflow.com/questions/31166747/jekyll-default-page](url)
i.e.

- Create a new file under the _pages folder called "articles.md"
- Find "index.html" under the root directory and copy and paste its contents into "articles.md"
- Copy and paste the contents of your current about page into "index.html"

In essence, this "swaps" the about page with the current front page with articles. I hope this helps!

**Comment by amitmerchant1990** [comment]
Thanks @codestin!
