### ISSUE TITLE
Font licensing

### ISSUE THREAD

**Issue by WorldMaker** [amitmerchant1990/reverie#2]
Futura PT is a commercial font that needs commercial font licenses paid for its use. Distributing it in this repository is likely a copyright violation, and you should consider switching to an openly licensed font.

https://www.myfonts.com/fonts/paratype/futura-book/

One resource for finding fonts appropriately licensed for open web usage is Google Fonts: https://fonts.google.com/

Semi-related you should be aware that using "Light" weights of fonts for body text can make long-form reading tough, which may be the opposite of what you want in a blog setting.

**Comment by amitmerchant1990** [comment]
Stopped using FuturaPT fonts from this commit onwards: f831df5428633ffe0f9a62bf31b0bcdc76e765a7
