### ISSUE TITLE
Funding is setup incorrectly

### ISSUE THREAD

**Issue by idbrii** [amitmerchant1990/reverie#20]
Clicking the "Sponsor" button on this github page gives an error:

Some errors were encountered when parsing the FUNDING.yml file:

Some users provided are not enrolled in GitHub Sponsors. Apply to Sponsors.
Learn more about formatting FUNDING.yml.

Maybe you need to remove the github line until you're accepted into their funding program?

**Comment by amitmerchant1990** [comment]
I'd like to keep it as it is as this doesn't seem to harm this project anyway.
