### ISSUE TITLE
Code always has double scrollbars

### ISSUE THREAD

**Issue by idbrii** [amitmerchant1990/reverie#21]
If you use code (indent 4 spaces or triple backquote fenced code), you get two sets of scroll bars around your code. Occurs on the [demo page](https://www.amitmerchant.com/reverie/introducing-reverie-jekyll-theme/) too:
![image](https://user-images.githubusercontent.com/43559/72649979-ebc6a180-3933-11ea-902b-7c712788be05.png)

I would expect that code to have no scroll bars. Code that is too wide for the page should have only the necessary scroll bar (horizontal) and only one of them.

Looks like [the code looks like this in the source](https://github.com/amitmerchant1990/reverie/blob/master/_posts/2019-02-13-introducing-reverie-jekyll-theme.md):

    ```md
    categories: JavaScript
    ```

Since it happens in the demo, I assume this is a bug and not me doing something wrong.

Occurs in both browsers I tested:

* Chrome Version 79.0.3945.117 (Official Build) (64-bit) (in incognito)
* Microsoft Edge 44.17763.831.0 with Microsoft EdgeHTML 18.17763

**Comment by idbrii** [comment]
Confirmed fixed.

Weirdly, I still had double scrollbars even after seeing my latest content on github, but refreshing a few times seemed to fix it. Maybe Chrome had locally cached the style.css? Oh well.

Thanks!

**Comment by patricsteiner** [comment]
You're welcome, happy to help 😃
Yeah, very likely that Chrome just cached the css. I usually reload with [CTRL] + [F5] to assure everything is re-fetched from the server.
