### ISSUE TITLE
styles.scss invalid US-ASCII character

### ISSUE THREAD

**Issue by agardnerIT** [amitmerchant1990/reverie#24]
I'm using reverie as a base for my site. When running this locally with:

```
bundle exec jekyll serve
```

I get:

```Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':```

I don't have that file in my code so I assume it's pulling it from the upstream (this repo).

**Comment by amitmerchant1990** [comment]
If you are running it locally, how could it be using upstream?
