### ISSUE TITLE
Where is header.html ?

### ISSUE THREAD

**Issue by armsp** [amitmerchant1990/reverie#25]
I wanted to edit the looks of `header.html` that is responsible for the topmost header - 
![image](https://user-images.githubusercontent.com/12681262/79061189-2d54b780-7cab-11ea-973a-0c203188fdad.png)

I can see that in `_layouts` folder, in `default.html` you include `header.html` but I don't see that file in `_includes` folder -
```html
<!DOCTYPE html>
<html lang="{{ page.lang | default: site.lang | default: "en" }}">

  {% include head.html %}

  <body>

    {% include header.html %}

    <main class="page-content" aria-label="Content">
      <div class="wrapper">
        {{ content }}
      </div>
    </main>

    {% include footer.html %}

  </body>

</html>
```
How are you including `header.html` ?

**Comment by patricsteiner** [comment]
Are you sure you have the correct  version? When I check the _layouts/default.html, I cannot see a header include:
https://github.com/amitmerchant1990/reverie/blob/master/_layouts/default.html

**Comment by armsp** [comment]
Strange that it would happen. I checked with the latest release and it seems okay now. Closing this.
