### ISSUE TITLE
Not able to set up locally

### ISSUE THREAD

**Issue by therajanmaurya** [amitmerchant1990/reverie#27]
It is great that whenever I make changes. It is working fine but It's not good practice to commit and push the code on GitHub to see the changes. 

I tried to running locally but it's not working.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5724482/79098909-9b1ee300-7d80-11ea-8a8b-4a118564d8e2.png">

**Comment by amitmerchant1990** [comment]
Well, in order to run this locally, you'd first need to install Ruby and Jekyll into your system.

I'd like you to check this article: https://leimao.github.io/blog/Jekyll-Site-Locally/ for starters.

**Comment by Harald-U** [comment]
FYI
I found an easy way to test locally using a Docker image. I described it here:
https://haralduebele.github.io/2021/02/15/Test-your-Github-Pages-content-locally/
