### ISSUE TITLE
How to use pullquotes and modify the style of quotes?

### ISSUE THREAD

**Issue by athletik** [amitmerchant1990/reverie#39]
Hi,

Thanks for your edition of Reverie!

I'm fairly new to anything tech related so my questions may well be dumb:

1. What's the syntax to create a pullquote while writing a .md page?
2. How can I change the background colour of the quotes created by the regular "> " method?

Thank you again for your attention!

**Comment by confor** [comment]
Hello,

1. I believe the syntax for a pullquote is `<span data-pullquote="your text here"></span>`. You can also use liquid syntax: `{% include pullquote.html quote="your text here" %}`
2. To change the blockquote background color you need to modify the `background-color` property in `.post blockquote` located in `style.scss` line 381 ([link here](https://github.com/amitmerchant1990/reverie/blob/master/assets/style.scss#L381)) which by default is `#ede1ff`, a kind of gray-ish pink.
