### ISSUE TITLE
Hardcoded property in meta.html

### ISSUE THREAD

**Issue by orhun** [amitmerchant1990/reverie#47]
There's a hardcoded property (`og:site_name`) in meta.html which might be overlooked while creating forks:

https://github.com/amitmerchant1990/reverie/blob/83727d296f188de40cb603df66c6d2ee98ac2bc7/_includes/meta.html#L26

Maybe you can edit this property out or add a disclaimer to README.md.

Just FYI :)

**Comment by amitmerchant1990** [comment]
Hey @orhun nice find! I'll fix it. Thanks for the heads up!

**Comment by amitmerchant1990** [comment]
I have removed that meta tag as it was no longer relevant.
