### ISSUE TITLE
Mastodon comment section

### ISSUE THREAD

**Issue by msirringhaus** [amitmerchant1990/reverie#49]
Hi, 
there is a nice way to add a comment section via Mastodon (found [here](https://carlschwan.eu/2020/12/29/adding-comments-to-your-static-blog-with-mastodon/))

I've added this to my page with [this commit](https://github.com/msirringhaus/msirringhaus.github.io/commit/f7fcdde0285ca0d1933d3d571be9e757c36ff063) in case you (or anyone else) is interested.

**Comment by amitmerchant1990** [comment]
Thanks for the suggestion but I'm not planning to implement it at this moment as Maston is still used by a very small set of people.
