### ISSUE TITLE
Creating from the template not working

### ISSUE THREAD

**Issue by pdwaggoner** [amitmerchant1990/reverie#51]
Hi - I clicked the use from template button to create my site from the template, and it's not elegant or working... This is all I've done. Not sure why it's not working. Take a look: <https://pdwaggoner.github.io/> Any help is welcomed. Thanks!

**Comment by hopeful-lemon** [comment]
Did you rename your repository to "yourgithubusername.github.io" as stated in the getting started section ?

**Comment by pdwaggoner** [comment]
I did. And a few other attempts and tricks. No success. But it's not a huge thing; just used another theme. Thanks!

**Comment by hopeful-lemon** [comment]
You're very welcome !
