### ISSUE TITLE
Code blocks dont have rounded corners 

### ISSUE THREAD

**Issue by siduck** [amitmerchant1990/reverie#56]
Default : 

![image](https://user-images.githubusercontent.com/59060246/117656233-bba0b300-b1b5-11eb-9bb7-cc314f178445.png)

Codeblocks should have rounded corners like this :

![image](https://user-images.githubusercontent.com/59060246/117656349-df63f900-b1b5-11eb-87bc-f7d5ba888248.png)

**Comment by confor** [comment]
Simply add `border-radius: 7px` to the stylesheet. I'm not sure what theme is in your screenshot but it should be added to `.highlight {}` in your corresponding file

https://github.com/amitmerchant1990/reverie/blob/4d009f2037b3fc472df14502ea353a413d87db22/_sass/_darcula.scss#L1-L6

https://github.com/amitmerchant1990/reverie/blob/4d009f2037b3fc472df14502ea353a413d87db22/_sass/_highlights.scss#L2-L7

Example:
![image](https://user-images.githubusercontent.com/38121691/141522604-df07c62f-d4b8-41f2-b6cb-87b788eb82a2.png)
