### ISSUE TITLE
Add support for Mastodon URL in socials 

### ISSUE THREAD

**Issue by namespace-dave** [amitmerchant1990/reverie#69]
Given the current demise of Twitter, and the rise of Mastodon, it would be great to have the option to define a Mastodon profile URL, represented by an icon. 🤞

**Comment by dan-han-101** [comment]
I got this working in a fork of mine. 
https://github.com/dan-han-101/programmerdays.github.io/commit/736b247b661f1c1508ecffaebbbaf4ae0fe5e9a0
You can see it in action here, 
https://programmerdays.com/
See the footer, last icon in the list. 

If you'd like, I can send a PR to this repository with an update.

**Comment by neely** [comment]
I think adding the base64 encoding to /_sass/_svg-icons.scss would be the easy step, then mod config.xml.

That said, I haven't done this, but would also appreciate the addition.

**Comment by dan-han-101** [comment]
Added a PR for you to review.
