### ISSUE TITLE
Support empty titles

### ISSUE THREAD

**Issue by pflenker** [amitmerchant1990/reverie#9]
Do you plan to support posts with empty titles? If so, I could open a pull request if you are interested. I am falling back to the excerpt if no title is given.

**Comment by amitmerchant1990** [comment]
That's a great idea! You can go ahead and raised a PR. I'll see if we can proceed with it or not.

**Comment by pflenker** [comment]
Here it is: https://github.com/amitmerchant1990/reverie/pull/10
